extends:
  - prettier
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
env:
  # TODO: find out how to turn this on only for src/**/*.test.js files
  jest: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  # TODO: Remove this when we have shifted away from the async package
  no-shadow: 'warn'
  prettier/prettier: "error"
  '@typescript-eslint/no-explicit-any': 'off'
